# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app tuppr
  namespace: "${KS_NAMESPACE}"
spec:
  targetNamespace: &namespace system-upgrade
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/system-upgrade/tuppr/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: "${KS_GIT_REPO_NAME}"
  wait: true
  interval: "${KS_INTERVAL}"
  retryInterval: "${KS_RETRY_INTERVAL}"
  timeout: "${KS_TIMEOUT}"
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tuppr-upgrades
  namespace: "${KS_NAMESPACE}"
spec:
  targetNamespace: system-upgrade
  commonMetadata:
    labels:
      app.kubernetes.io/name: tuppr
  dependsOn:
  - name: tuppr
  - name: kuberhealthy
  path: ./kubernetes/apps/system-upgrade/tuppr/upgrades
  prune: true
  sourceRef:
    kind: GitRepository
    name: "${KS_GIT_REPO_NAME}"
  wait: false
  interval: "${KS_INTERVAL}"
  retryInterval: "${KS_RETRY_INTERVAL}"
  timeout: "${KS_TIMEOUT}"
