# yaml-language-server: $schema=https://k8s-schemas.pages.dev/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: r2
spec:
  configuration:
    destinationPath: s3://cloudnative-pg/
    endpointURL: ${R2_ENDPOINT}
    serverName: postgres17-v1
    s3Credentials:
      accessKeyId:
        name: cloudnative-pg-secret
        key: aws-access-key-id
      secretAccessKey:
        name: cloudnative-pg-secret
        key: aws-secret-access-key
    data:
      compression: bzip2
    wal:
      compression: bzip2
      maxParallel: 8
  retentionPolicy: 30d

