# yaml-language-server: $schema=https://k8s-schemas.pages.dev/barmancloud.cnpg.io/objectstore_v1.json
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: nas
spec:
  configuration:
    destinationPath: s3://cnpg-backups/
    endpointURL: http://garage.storage.svc.cluster.local:3900
    s3Credentials:
      accessKeyId:
        name: cnpg-garage-secret
        key: ACCESS_KEY_ID
      secretAccessKey:
        name: cnpg-garage-secret
        key: ACCESS_SECRET_KEY
    data:
      compression: bzip2
    wal:
      compression: bzip2
      maxParallel: 4
  retentionPolicy: 30d
  serverName: postgres17-v1

