# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: garage-config
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: garage-config
    template:
      engineVersion: v2
      data:
        garage.toml: |
          metadata_dir = "/var/lib/garage/meta"
          data_dir = "/var/lib/garage/data"
          db_engine = "lmdb"
          metadata_auto_snapshot_interval = "6h"
          replication_factor = 1
          compression_level = 1

          rpc_bind_addr = "[::]:3901"
          rpc_secret = "{{ .RPC_SECRET }}"

          [s3_api]
          s3_region = "garage"
          api_bind_addr = "[::]:3900"
          root_domain = ".s3.garage"

          [s3_web]
          bind_addr = "[::]:3902"
          root_domain = ".web.garage"
          index = "index.html"

          [admin]
          api_bind_addr = "[::]:3903"
          admin_token = "{{ .ADMIN_TOKEN }}"
  dataFrom:
  - extract:
      key: garage
