[tools]
kubectl = "1.35.1"
sops = "3.12.1"
age = "1.2.1"
task = "3.44.0"
flux2 = "2.8.0"
talhelper = "latest"
talosctl = "1.12.4"
krew = "0.4.5"
"npm:renovate" = "latest"

[env]
KUBECONFIG = "{{config_root}}/kubernetes/kubeconfig"
SOPS_AGE_KEY_FILE = "{{config_root}}/age.key"
K8S_AUTH_KUBECONFIG = "{{config_root}}/kubernetes/kubeconfig"
TALOSCONFIG = "{{config_root}}/talos/clusterconfig/talosconfig"
