# yaml-language-server: $schema=https://k8s-schemas.pages.dev/notification.toolkit.fluxcd.io/provider_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: github-dispatch
spec:
  type: githubdispatch
  address: https://github.com/shamubernetes/home-k8s
  secretRef:
    name: github-token-secret
