apiVersion: v1
kind: ServiceAccount
metadata:
  name: ghar-set-zoo
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: ghar-set-zoo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: ghar-set-zoo
    namespace: actions-runner-system
