# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: homelab-assistant
  namespace: flux-system
spec:
  interval: 30m
  url: https://rafaribe.github.io/homelab-assistant
