# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1.json
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: kuberhealthy
  namespace: flux-system
spec:
  interval: 2h
  url: https://kuberhealthy.github.io/kuberhealthy/helm-repos
