# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./actions-runner-controller.yaml
- ./backube.yaml
- ./bjw-s.yaml
- ./cilium.yaml
- ./cloudnative-pg.yaml
- ./csi-driver-nfs.yaml
- ./coredns.yaml
- ./descheduler.yaml
- ./emberstack.yaml
- ./external-dns.yaml
- ./external-secrets.yaml
- ./grafana.yaml
- ./ingress-nginx.yaml
- ./jetstack.yaml
- ./kuberhealthy.yaml
- ./kyverno.yaml
- ./metrics-server.yaml
- ./node-feature-discovery.yaml
- ./onepassword.yaml
- ./openebs.yaml
- ./piraeus.yaml
- ./postfinance.yaml
- ./prometheus-community.yaml
- ./rook-ceph.yaml
- ./spegel.yaml
- ./stakater.yaml
