# yaml-language-server: $schema=https://k8s-schemas.pages.dev/source.toolkit.fluxcd.io/helmrepository_v1beta2.json
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: onepassword
  namespace: flux-system
spec:
  interval: 5m
  url: https://1password.github.io/connect-helm-charts/
