# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tracearr
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: tracearr-secret
    template:
      engineVersion: v2
      data:
        # App
        COOKIE_SECRET: "{{ .TRACEARR_COOKIE_SECRET }}"
        DATABASE_URL: "postgresql://{{ .TRACEARR_POSTGRES_USER }}:{{ .TRACEARR_POSTGRES_PASSWORD }}@postgres17-pooler.database.svc.cluster.local:5432/tracearr?sslmode=disable"
        ENCRYPTION_KEY: "{{ .TRACEARR_ENCRYPTION_KEY }}"
        JWT_SECRET: "{{ .TRACEARR_JWT_SECRET }}"
        MAXMIND_LICENSE_KEY: "{{ .MAXMIND_LICENSE_KEY }}"
        REDIS_URL: "redis://dragonfly.database.svc.cluster.local:6379/15"
        # Postgres Init
        INIT_POSTGRES_DBNAME: tracearr
        INIT_POSTGRES_HOST: postgres17-pooler.database.svc.cluster.local
        INIT_POSTGRES_USER: "{{ .TRACEARR_POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .TRACEARR_POSTGRES_PASSWORD }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
  - extract:
      key: cloudnative-pg
  - extract:
      key: maxmind
  - extract:
      key: tracearr
