apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:J7yAvBLcxgIcR4T0xLaoH8e/D/k2kfBQgh1Hx26h7poHVqwD,iv:6xht+kBpp6rgUqpcuihROTiruzICEfEj6eu5bSorHkg=,tag:1O35YqtYeIfzNvWKSeRFZA==,type:str]
  credentials.json: ENC[AES256_GCM,data:GbfCmeJFnXbOySUQHiBIvrAR+SC9UFxHWD6ee8rvbT5JH57tTHai92XkcaJDn6t5alawRCY/cyYd3i4weXt62ZYhBlt5UPeBNH9K8g4fCmJe301P1JHm9pOU2K9wJNauDfLbGbFrA84wQcdkCyvdVX5moO1Ec10nLgaLuiV4+aSBr1tR+F3dG3MHnUsqiaPQuvyqIzGJJ0cJgaArIT9YtzwQfQOWCm/KOeUDbjroAA==,iv:iqFmdzwX+Riw9Sid3c0Y5bAqcXKC8Yopyvl7QG3MqoE=,tag:fT1zVybCqw4xw+mheTWXog==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMeDYwc285WnB0dEVHdHYw
      bjhNdzBVc1d0Tk5UTDZmOTZhRCt0ejcwRkhnCmgvQk5SWlhhWjRCNUI2a0ViTHJG
      WjV6L09YMCtCS0Qrd3NXbEdiN0p5YTgKLS0tIHIwZm1tbW5hWE1xTjk0blFKa2t4
      UnRIcFV0Ym9qb2E4Ny92SHkrZ1hDWGcKa0d9RrSD4aZRKRpSJ4M2krNJIOhRui4j
      3v951ypJ5qLWI/5kJasadmBmKOG+J97y9JBVA4QIkYZBJ7I6bkXGxw==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-19T23:19:18Z"
  mac: ENC[AES256_GCM,data:XcJjJHuU7KXWBE4tS56jh7uGQBypE0GnLn9CfUhnVBjGXd/zVxVX2NksAjY9UGBUeFKLBMWnjk546RIse0zxbzT71CQUUDPji9y60vHNsa6anI8GQRtoPaLiUdkKAr7Zqxpcy850qm75sCUPbMP3tHdFiZfcPY1MP0Q4JFpbHFU=,iv:ksqPhbSn0DQ9Z0k0CUVv8LBnMzQUviT2+KbzA9lBZGs=,tag:I58a7jsKO858k03OuEratw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
