# yaml-language-server: $schema=https://k8s-schemas.pages.dev/notification.toolkit.fluxcd.io/alert_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Alert
metadata:
  name: pagerduty
spec:
  providerRef:
    name: pagerduty
  eventSeverity: error
  eventMetadata:
    cluster: titans-k8s
    env: production
  eventSources:
  - kind: Kustomization
    name: "*"
  - kind: HelmRelease
    name: "*"
  - kind: GitRepository
    name: "*"
  - kind: HelmRepository
    name: "*"
  - kind: OCIRepository
    name: "*"
  - kind: HelmChart
    name: "*"
  - kind: Bucket
    name: "*"
  - kind: ImageRepository
    name: "*"
  - kind: ImagePolicy
    name: "*"
  - kind: ImageUpdateAutomation
    name: "*"
