# yaml-language-server: $schema=https://k8s-schemas.pages.dev/notification.toolkit.fluxcd.io/provider_v1beta3.json
apiVersion: notification.toolkit.fluxcd.io/v1beta3
kind: Provider
metadata:
  name: pagerduty
spec:
  type: pagerduty
  address: https://events.pagerduty.com
  secretRef:
    name: pagerduty-token-secret
