# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./tautulli-check.yaml
configMapGenerator:
- name: plex-check-script
  files:
  - plex-check.sh=./scripts/plex-check.sh
generatorOptions:
  disableNameSuffixHash: true
