# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minecraft-stoneblock4-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: minecraft-stoneblock4-credentials
    template:
      engineVersion: v2
      data:
        cf-api-key: "{{ .CURSEFORGE_API_KEY }}"
        rcon-password: "{{ .RCON_PASSWORD }}"
  dataFrom:
  - extract:
      key: minecraft
