---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-credential-onepassword
  namespace: services
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: n8n-credential-onepassword
    template:
      engineVersion: v2
      data:
        token: "{{ .credential }}"
  dataFrom:
    - extract:
        key: 1Password Connect
---
apiVersion: n8n.n8n.io/v1alpha1
kind: N8nCredential
metadata:
  name: onepassword
  namespace: services
spec:
  n8nInstance:
    serviceRef:
      name: n8n
      namespace: services
      port: 5678
    apiKeySecretRef:
      name: n8n-api-key
      key: api-key
  credentialName: "1Password Connect"
  credentialType: "onePasswordApi"
  deletionPolicy: Retain
  secretRef:
    name: n8n-credential-onepassword
  data:
    baseUrl: "http://onepassword-connect.op.svc.cluster.local:8080"
  fieldMappings:
    token: token
