---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-api-key
  namespace: services
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: n8n-api-key
    template:
      engineVersion: v2
      data:
        api-key: "{{ .api_key }}"
  dataFrom:
    - extract:
        key: n8n API Key
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: n8n-credential-postgres
  namespace: services
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: op-secret-store
  target:
    name: n8n-credential-postgres
    template:
      engineVersion: v2
      data:
        host: postgres17-pooler.database.svc.cluster.local
        port: "5432"
        database: n8n
        user: "{{ .N8N_POSTGRES_USER }}"
        password: "{{ .N8N_POSTGRES_PASS }}"
  dataFrom:
    - extract:
        key: n8n
---
apiVersion: n8n.n8n.io/v1alpha1
kind: N8nCredential
metadata:
  name: postgres
  namespace: services
spec:
  n8nInstance:
    serviceRef:
      name: n8n
      namespace: services
      port: 5678
    apiKeySecretRef:
      name: n8n-api-key
      key: api-key
  credentialName: "Postgres account"
  credentialType: postgres
  deletionPolicy: Retain
  secretRef:
    name: n8n-credential-postgres
  fieldMappings:
    host: host
    port: port
    database: database
    user: user
    password: password
