---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: n8n-operator
  namespace: services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: n8n-operator-manager
rules:
  - apiGroups: [""]
    resources: [configmaps, secrets]
    verbs: [get, list, watch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [""]
    resources: [persistentvolumeclaims, services]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [apps]
    resources: [deployments]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [monitoring.coreos.com]
    resources: [servicemonitors]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [n8n.n8n.io]
    resources: [n8ncredentials, n8ninstances, n8nworkflows]
    verbs: [create, delete, get, list, patch, update, watch]
  - apiGroups: [n8n.n8n.io]
    resources: [n8ncredentials/finalizers, n8ninstances/finalizers, n8nworkflows/finalizers]
    verbs: [update]
  - apiGroups: [n8n.n8n.io]
    resources: [n8ncredentials/status, n8ninstances/scale, n8ninstances/status, n8nworkflows/status]
    verbs: [get, patch, update]
  - apiGroups: [networking.k8s.io]
    resources: [ingresses]
    verbs: [create, delete, get, list, patch, update, watch]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: n8n-operator-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: n8n-operator-manager
subjects:
  - kind: ServiceAccount
    name: n8n-operator
    namespace: services
