# yaml-language-server: $schema=https://k8s-schemas.pages.dev/networking.k8s.io/ingress_v1.json
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: authentik-outpost
  annotations:
    external-dns.alpha.kubernetes.io/target: internal.${HOME_DOMAIN}
spec:
  ingressClassName: internal
  rules:
  - host: auth.${HOME_DOMAIN}
    http:
      paths:
      - path: /outpost.goauthentik.io
        pathType: Prefix
        backend:
          service:
            # Authentik Embedded Outpost service
            name: ak-outpost-authentik-embedded-outpost
            port:
              number: 9000
