# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./rbac.yaml
- ./secretstore.yaml
- ./objectbucketclaim.yaml
- ./externalsecret.yaml
- ./configmap-blueprints.yaml
- ./ingress-outpost.yaml
- ./helmrelease.yaml
