# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./namespace.yaml
- ./media-nfs.yaml
- ./sabnzbd/ks.yaml
- ./radarr/ks.yaml
- ./radarr-3d/ks.yaml
- ./sonarr/ks.yaml
- ./profilarr/ks.yaml
- ./prowlarr/ks.yaml
- ./seerr/ks.yaml
- ./bazarr/ks.yaml
- ./wizarr/ks.yaml
- ./whisparr/ks.yaml
- ./cwa-bdl/ks.yaml
