# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/master/persistentvolume-v1.json
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: arrs-media-nfs
spec:
  storageClassName: arrs-media-nfs
  capacity:
    storage: 140Ti
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    volumeHandle: arrs-media-nfs
    volumeAttributes:
      server: "${IPAM_IP_NFS}"
      share: /mnt/user/Media
  mountOptions:
    - nfsvers=4.2
    - nconnect=16
    - hard
    - noatime
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/master/persistentvolumeclaim-v1.json
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-nfs
  namespace: arrs
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: arrs-media-nfs
  resources:
    requests:
      storage: 140Ti
