# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/master/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
  name: games
  annotations:
    kustomize.toolkit.fluxcd.io/prune: disabled
