# trunk-ignore-all(trunk-yls/no-yls)
apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
  namespace: flux-system
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:th9UEt7646zm7vjr,iv:CN0WOhB3pEsiRHbe0g33zTll52UbXTrogY73Nzk34VY=,tag:q+u8FTP+IFxy2SYF9NeTQQ==,type:str]
  SECRET_ACME_EMAIL: ENC[AES256_GCM,data:GYgKrHFaN8KjT5rEQysoqP1QuwZL,iv:l1aAC6P+HR93gjdflnTjMUCmfiUwfYvjpj8bvqXSwfA=,tag:tWpF1atpNtPfTyphjcuDAw==,type:str]
  SECRET_CLOUDFLARE_TUNNEL_ID: ENC[AES256_GCM,data:blDvws2EaGIfeeyUuGhajgmaA1VD0zrI2QPaRnfI0TmS2Swg,iv:8G7G6tD9saj5AhELlhiASE8egqzit1ZVjp2awZs2RA8=,tag:Jvafwm4x4K8KWEZZUD7BUg==,type:str]
  SECRET_EXTERNAL_SECRETS_PASSWORD: ENC[AES256_GCM,data:AVoLhmhAdSdQL8GYdcLZ3JeaGwxr9RYIKGY+unEF6NPQnnP+3HtKueoVn2q+NgN3jdeXKgjAG2ElTP7Diy3pZF26VNzdl55qP78cKtVkp1EGDSlYFXmRQwdyogLtkAz6ByQjZnu9Mx4yESZmzAOo5vzY+rwvycw7OuodwZnvVlbo5mXhbYXRBW2QZO0KzxSVR3+Ija+96kwYHpjjjLZt6SRJOs90Oxkb6riYkV98xHTEj9KxY+cHhhd+mBHvyRud1N48pCSuGWZ5PeUqkTSgdRHmbxzZY5v/CWZbmkQKXpwYUUriAEWGXAQ8Z2pP29Wt5iT0JOoEYeCBodtJSTwRMcsoufYldRKaPP7QOQXWu7BhAh5u8/qZSm9AQUv357kwqyJQ1Yb4m6hQ6t7DqZKyYYcQOp20C/ldwQ/mjIwZllqBOswZnBk47IKA5Vw43XEY+s7bc2D+GSH8301z30DXOM9pzGERsMNkDzJKcr/TVA6mRf4tsuJvmn5aKNqLy+rNI1/+5VLfqIVyy5qTkq1t5tLhX+vJoKy4Hz4J0SLcMU4+UOE1rswFudHxI2fepcr++30NhcxXnVZNo5ljA/PUr5rWOpkpW0jMIJ2k46GJPvAhu921YNCSLWOL4upg0ZbYCfhDrUpFo5lTbZckApswZFzx0ejAz8NeyW/jd7zL8hjn9LkUFa50h52U9xfiXPDxc8QZQ7SdBcSDHTQ49jwaRkj8Pv44QRLq4MxLm6sEJ20YXmksKwxJxG9oXN7GuzJ00ku1yWPR9Yok7pT5zhYoUelovTbM+WppMaNG5DVwE1RGexqptqBe2gj6H8fisMOrKF/y40/A/menmdDtky43HcxP5vsp,iv:dSSOUJbTlt6y2YBb37K0zu+hAAUvfYi0C+xQ3On4Pag=,tag:/RYcc3+K5RFfvq71qJqDSw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3d1Y0ek1NNzlkQnVxTEpt
      cXdiQlFRREtINnpVMmM3L0RnR0lhL0xiWEZRCitURjUvLy9qc05NKzgrOXBOUllT
      V2UwTDg4aVRFbDVtYTRETTR3dkxXTkkKLS0tIDVtNEVrR2t0TU9XUlJjbzFOTlJn
      ZDZiRFhzZENQSzV2QlIwV1l1UlF2bE0KPkWOqpQ4dZ7ChPGAnbLYi+rfd5MJfIww
      uIswIV+mCH8pnIGMsmFWb55ovETYX+GCrNlJU3zPo74TDGqCn7w9fw==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-19T23:19:18Z"
  mac: ENC[AES256_GCM,data:wBaq+bWk1HNnl9DwXYQ3o8AfKOf2p5da/+jCP/zNb6op/FjduxntD9P856/W6V2qZBFYhx4Msjw7wr4+qggXzBl8WLw/EEZldUR7eP8xD6GKuEqtXGrG7rjunW96jmfH3FOUu8Gd+LOrz64J6ZuCD845Ibgk2eYpvKOvWW6sXzI=,iv:UD659QXvj+GvK6ul/o3Ccutah5nY1Ke+ZDGFb01dWOc=,tag:xRNeAHWFnNWGzDlmf6wfOQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
