# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/master/configmap-v1.json
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "America/New_York"
  KS_NAMESPACE: "flux-system"
  KS_INTERVAL: "30m"
  KS_RETRY_INTERVAL: "1m"
  KS_TIMEOUT: "5m"
  KS_GIT_REPO_NAME: "home-kubernetes"
  REPO_NAMESPACE: "flux-system"
