# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./cluster-settings.yaml
- ./cluster-ipam.yaml
- ./cluster-secrets.sops.yaml
- ./volsync-schedules.yaml
- ./op-credentials.sops.yaml
- ./op-connect-token.sops.yaml
