# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/master/namespace-v1.json
apiVersion: v1
kind: Namespace
metadata:
    name: op
# yamllint disable-line rule:document-start
sops:
    age:
        - recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacnZwT2FpQTRhK3V1Ymhm
            ZCtzQ3kwMFJaN3dpVUF4dTByZEVsUVV4QzBBCkYyN2V4cjNMZjU5N2oxN3ZsKzY3
            K0FuSko2MWwzNmRZQ3VVR3o4WmhsQnMKLS0tIHE2aWF5Mm1tMEhpMVZYSmMrd2Iv
            czJiV0hZUHRzb1FEZURiSTBPZjA2ZUEKbrwlykoDIYDR3WNMhQPqlRinqsVtme4q
            NlwAg13hH/nYGgKiKrgWiBPHyC2kioxTbLuIohw08qXbB9dhZLqefQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T22:29:06Z"
    mac: ENC[AES256_GCM,data:RbFGIVDzn0vP0hIyYy2MpWAESTBXBezRJJ566IgnmF0DcWEmdhcwndte2Es47vHKpMIKTGYagBqIgnx9x2BOWWZ2q5DVFby73U98cKlNs78Eh1/cVAfcMdvw7xm9GwPXucGeSpcDjikpEJ0W9w4vbr1gY77IxSyq+PKp/Y+pcHI=,iv:e403bLyY8aVIKqUDnC4OP9WyZpzI09RCyRRQ+0TdvSU=,tag:rWC3s8I7jyKmgNcFOTB/lw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/master/secret-v1.json
apiVersion: v1
data:
    1password-credentials.json: ENC[AES256_GCM,data:oYaBHJ9Ph3Lgmyodc8fuAPftw43V3vFELqR0uFew5AyTES73ydq2JJ6ldwk+kqJ4d0TSDVN4vtXHw6rkUQO8XL1x6UWFYDd9AU1uMP0FiFNKUpaJDSjtqyPcjInAZLdB8bYyPSAga/aU2Qsde9yPy2oT8O70j9K2Jbgu14fQik2Ue8KGGVGVKOrzTFx9b52AlAgHlcENKpQqITwrTh0D/VyAwLOFAX6RVuQ76/D7ou8LMIEtHZcA2LoE6vaSBAHWsS+xaDmR5uyhBOZo/nAKgTL6ZoCDQB67tH5u2U9d9EUqvtHhTud9M/goPc8v9fH3xA+0U7lSPojDiH+GfbEleYhRhqe9UzACBetEMoMpxm/Xp35YskcXJd5VgmXMSeo+b53fiHUqiwOJVczqhAF2OlRssp/1nPFdxIBPhxar5cCfk3tyAwserl5hlOmnrTfJp2Fe5+FnLzyvUXuGrJuT/2i1zlu3Ekq+5CDtijE6U1odYEhdipXQ5/N2SA4wYZxX4fQJZHBn8I/+8KoPsphqEwJMDMPuXkiX40WSlIwz35H+x7SwiQ0N3kaa5lHa12Ao9G5z6/ajtWR8PrMiDLVt0b2eSuYfEg22y8KnAA+Fn0l0/BbKKKWhT88vRUyo/Zo+sieVn53ggNhvKWe/uiWwjN2TYVN7eIlv6NwRVuRDfPLpWoIJbQrkkd0lPg4JRHGA6sPNpkR36C2qa3Be+Lg49LxaSS8KTvkMEUUlgd0fokIxKtr16GbmM/J0vh1bpc81kEN9cRbbU4/S8Mz0x/IKJG9bw6ptQ3HfyhB8s8ikKvHu11Teo85IdRnL6uXcm2Vu56m7bZnpIHe+yP6uLzR/1P+WQw/KK+g3Vi/ugeKUerIMubNvmI2C8V4+OEx/pdjDxcdjNZn3TwUO/tOGzr/BIT658hR9no/MWIf+iHa1IoTGNVR0r3kFf14tNhTtW5exTXKO/IKstO7hZuui8bLKkBKrRsbhqKk34MEm/iaCK6llaWyuFlZELtkWJVvn7b2qSz1KWIicmqyM2ibiwnkVgQ/3NmBru9CaRSvgpgACA1BFIX1xzZsSSG2dP/EC8SXO++7vec6XLoasDflr13nqkd6RrdzCV0w/lPArMVZF1C1VkqwW07PEdV1155dbvnq6VioUYxbZ1PErVGUVJBWyIsF8+HHdHwU50zHhQZr/7uqFF7ZqrNnedEYqrtVC0jVyJoU0hr/x+hc7KoLc/+HrCl/luOKJ6060Hxo6jqYwsqfy6lvXFVuF5PAMg35YOWMCZq7tJvKuKP+NQqUutYxPXj0WLd++II7urceZX/k52vTp/4z98viw2n0u1tJrnv6LmkwJVIj5oRg3SDY1IGjaCgo2lzPvLcO/vZQ9OXIaO165EIL7z2FRB2rqiar+JZ0FEtTFhuV5kSKUjqssbYj5rhh/m5UOqso+ENLDEFfbeg9KcVnPymEzwpgUA/fWPlHxxMqzlIyXkzKUNbfy/LdXcKZpokD/hOEIAV6wMmGeTfmm6PEZXqReVdn5AHC1xLNpoL/Am4dcphQGS7yU2Hl0kp/ieEYLW0ntPgFHwxXGRdP3o7QYrc0qhM1E5JKkHsuTOsNR6VhU4VqAk6/lRxiLXbRdFEeeO0BzNsZVU7bVXwR1c4D8mtWvuXWEAJjU5TJsONpWyJ3NRcd2KeHv4YvEtQFSEiB3Dd8+Ya3Yhh1zF1V+Woaw35EgKHZphzJCyHxhUEtz0cGcVQBbgt76eULY+IJNaR3fgZ+1Iz2ppwt8c0hqNkSNVsU0dIn8yq91QiurqnFIqa2ENMpHri4B8PC1F4AolSWo5uiWhZDM0APfEvwX3wNhwlth3r+yTo3axk2J0O81+x7PlDLfKJKtgDE1qrOGBWFxmaRls8NituyhWIkRn58QeliR7ZHjw3P2hpva1bPLqywou+HyrupE4amt9rNkvgxzsJLu6z+K9A2Qdts2La7UPhMVivcNbwX2hI4fj6xLhEWWhDtPJWWSsLSTl8DT9ymF2xt8,iv:xQcfxETd4sMm+pVSlHlyPhH5bFGGI5T9S6UsGvBl1pU=,tag:d4momK/sEFV6yRvQRA1hyg==,type:str]
kind: Secret
metadata:
    labels:
        app.kubernetes.io/component: connect
        app.kubernetes.io/instance: connect
        app.kubernetes.io/name: connect
        app.kubernetes.io/version: 1.7.1
    name: op-credentials
    namespace: op
type: Opaque
sops:
    age:
        - recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBacnZwT2FpQTRhK3V1Ymhm
            ZCtzQ3kwMFJaN3dpVUF4dTByZEVsUVV4QzBBCkYyN2V4cjNMZjU5N2oxN3ZsKzY3
            K0FuSko2MWwzNmRZQ3VVR3o4WmhsQnMKLS0tIHE2aWF5Mm1tMEhpMVZYSmMrd2Iv
            czJiV0hZUHRzb1FEZURiSTBPZjA2ZUEKbrwlykoDIYDR3WNMhQPqlRinqsVtme4q
            NlwAg13hH/nYGgKiKrgWiBPHyC2kioxTbLuIohw08qXbB9dhZLqefQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-02-13T22:29:06Z"
    mac: ENC[AES256_GCM,data:RbFGIVDzn0vP0hIyYy2MpWAESTBXBezRJJ566IgnmF0DcWEmdhcwndte2Es47vHKpMIKTGYagBqIgnx9x2BOWWZ2q5DVFby73U98cKlNs78Eh1/cVAfcMdvw7xm9GwPXucGeSpcDjikpEJ0W9w4vbr1gY77IxSyq+PKp/Y+pcHI=,iv:e403bLyY8aVIKqUDnC4OP9WyZpzI09RCyRRQ+0TdvSU=,tag:rWC3s8I7jyKmgNcFOTB/lw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
