apiVersion: v1
kind: Namespace
metadata:
  name: op
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWS3hFekRUYVl2QmtmWUdw
      Q0VKTUZCWjFxZHU5RWhOZG9wd3M2SEpnTXg0Cm15bkRHY01WYUV1YVhXanBMMG5P
      MUlyYTZmMWFOOXBXM2ovbTRwR21LU1kKLS0tIHNUK3lOWUdaZEw0RU9YTTYrSVE2
      VmRydnBaN0pHUktDS2MzNm9FeE9BODQKxs8aEUKfV5gtgh2gCVuUdB/ypLdsUZsH
      ab+zf0YKZiXCWdTvDx19G61IeVUNfORv+Olvxt39wmIa+Tsq63HzNw==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-20T01:25:43Z"
  mac: ENC[AES256_GCM,data:7aI/KeGQN9TsZBlOXYNwaDg+H+C82dbjCMwPcJSB9GO7GyfrEnowz1Bh60fyYM5OShgaq7kHx3LE4EOKBFEHPR8/IphJ8ALoOOmQgkLgp/GCeVn56QZBo+PGduR5FM5dPRM5lzom0VMlxcLLD3QcGisxE40FaTc5/skb0lhKh/E=,iv:asZeIShzpo58txcP3VTyYnqYhtlU7dYm673r8Faq3aA=,tag:hC6PIqvDWKce0cHXhXBI4w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
# yamllint disable-line rule:document-start
---
apiVersion: v1
data:
  1password-credentials.json: ENC[AES256_GCM,data:eEb5pUWzmp4ASpjrfwpxPAEbngNsQAZLLyAvJNmFlQvULNFbUFkLOyBM3nof/kSs60DnM5FDdyCl5tPHRGJL3H7n+Wphixes+QgTm1UfOmjZbqjZl9Fe1f/M9Fu4ktvcMtG+fs2+nQ6JylpVWSXhdcylzhKqlopgf6clRbS3E4J70JlPjqKEOsPIeQniCl1oIhL4K0ywcMRRFtEOxVPwW1NNUMlxM++/fzyAS9JM5pCccragWQT+EqJMccxErmVRTmZrMdFjoWWjTPcuGb0yQ6QPI/9TsMVvrpWsq/v6jQLypbr3alvWT0PojvqkHcRNWRCbyf5i4roExqN11sUUUzYjuZl7ks+E9Z5q7wg+fhFDsnbqFBjqJF6SmtJXPZ5mxwzqhCJN/IFyTL9Y5x+BmmgDFii3HBD+3xSLDod/zCS6bC8GJexZ6RXebw5jbDp09uj+aogZrEXxQJZrMqWTur9UOuv4839hQrW1Q9ThqibGV8GqjAz5e/Duay9M9AvQK4jpG4PuiyTahpbWbxXGXTO7C4+Cu9ajphEccKmg03d+vqSxLjUcH7Vs0V+D68SwiA4ong3K8oTV908/DfxKw/BhCRzBZpx4XoB9dE9U/a4rA3NZ8qgnlAb6dws4vrQTOeLOlqaB18L04J0TEPhwdiVmL57DpLucyaxF1IcbnW87Nz7EcWteg+gbPvCfXvlxNYeXulPtZUKIuO/GFhQMN1+P/kJvVuZirqBscaGntz/1VESwY2VEPVQ2tmRTYeAyQ7APZtzSl+rvfIVUCKm3p9nMA8fT92luKxR5PK2VbpPkbvnuuliTzmsSDjYTRcyVw+x0v7ZywbqzEmm6MTxRFGAc6LayLfBgjsD99mZvOJ7AxUuWbey01EPlMpBiTatMB11Wnmpkm6tt2W4mG2xd2sQOj9wy0wSGSLh/mJ14T9siRWKUlc+oXtqMlOnQ4VwQbTvbwcXwZo2jGRSPZTYf83z3AUjmO1OA3wpfHAyJnOr/glwyYNNeqq6ff7xvP/znvnEptmOXOpgWrEBPpIKBgR4C0FzkpIz2ClHxTlcOr4nBsoG9MSRg2kVdrAk/b8NmNXs5ANx6AOTabO8HAvPg8FPyH/Ok+QOc3zK3rSc650rg3ffCjxCCGH/Og5XfO1DbJsNqfHRJojbYAdUODkNkYxuiO49Dti2TEfOtHHERnFDyeIfW8D3yjNacXww+3ulCCpStpf1vWx2x+4krD3WdnFVZlitt/TAZCbJhzd/cpmFlwFpS1WGjvndTVKbKkQaGGKn/Z9h4iEF9YxpUC2uumk9iljDXj81eJfunuwMyWUpP7OhzZp3erG2rpMlpcIaNmvNcwYFWFdVk/O5Vb579wJCp6K5hq12gLapY16zMmI8gKO6BftRsoZ1BAc71FqtSBVKZpbEhfM2mcvkXjQOfocmyDqGOizrG6iOvAFggrcLscSCXTpAAA1WLggcK6XE7xq8RGlYtfJMHSVPo1+FjGAIcoLplEdjVaxrGHq9l+40KonsIiS57zCaRIuAQfOT1srIX0Xqc42D0XRbxYpLxX6L90Ri/UuTalOgDMIrV1xstjVLS4dH1khr17WPQQnv8WM8mawSdZ8Qa27YYLUXL06UdtRzsbxqjUAXHQYWncaqwXZHghfWC4SmIkFnZYOSg4kX6L6scx4Ilkza3B7c1CmYiUUcEGPcFwPikGF2VswoNUohyzye5+wb2JAZ7zPnbDE0STQlvUzatWXjosqwAu0ri2UbdlxKUeRyGHO2SpsMBa8VORku08lRFVIk1Gu2M+FUAsNSyvdDltCu6EPWhtH3Z+1k20w4B+eGaW1lpi/JBt48fl5znQgaARTd+H3CBN0olKSNZjqY8/prCNgkntO9y/LdS8D3Kuc8mLVrTg17PdvrHTvXFc0Brjx3zIa8GfVFABNXY7BLdRyXOi6+Xt87ib8Go+wEXf+RinwKxr0NLVIorhHwug4Mr+VIVT6E9ecen6+deHxqdN7PyKnWugvCDvyekmuT5dGruStFESAvLh6ewneDnMYSfGNTIIjvm56gG2sYil+ucz1tTe36Fzas++bZlRvY4NJRxEgcK3dDqo3knlCi+ABzQIxX0LsjSIxRVbW84u2gPvLI43ikwI/K7AtlsKTuh3EcFjEKRIqJ5PZeVQCnjLz5TC06pOYH/IHKGGkxhYjansDyM9FH0YomTD2EpzMcIkPiS+nYS03Rev1mxfe/eo3Wzdh9qbig/cXxyh7DkcN1VhxUw/1kvpZHMd94zeN3l2bDg9khztNV0jF5tO29tyQQwxi71EUKjhChXkcv+3O5WoBGwd2SA0SmDTBRQYa4PoTz010ZqCKCgLYfLIOMpvXN1OvoIGMJ1n6Ts6GHk3pQ1oJEcN3IGKhjTPolCzuIHKnMl1q8nY6MBYrwV0rDf4rlyNYD9wF2K5RLw69pTf05rBaL+gBLar1Sb3Py7MVCdkVn4APkF0DlwRvzgCNbISFtyyK5lSRUKM0leulBHcgTK51xuiEBdFlyK5KeNTJsuPGMlg30npHH6xZP54K2AX6VVXV/ZT/JE+9pw5S58h46Xf9MJuqghb6K95WuDq5U/cZe2pxB4QlsuBiia3i/lsF05n59lnYU89Lu0vYpx0zU1qd6t7kBaRv7OfTXNMguPJm6xr35s1lu8uR4aMVt1d5omsjHrJZmT,iv:ALYAoc6svqvjIo3dBt5h0sOo9evgwRbicO8ZzpVbC0w=,tag:dnZu+9x6lbJT592Fcg4K1w==,type:str]
kind: Secret
metadata:
  labels:
    app.kubernetes.io/component: connect
    app.kubernetes.io/instance: connect
    app.kubernetes.io/name: connect
    app.kubernetes.io/version: 1.7.1
  name: op-credentials
  namespace: op
type: Opaque
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWS3hFekRUYVl2QmtmWUdw
      Q0VKTUZCWjFxZHU5RWhOZG9wd3M2SEpnTXg0Cm15bkRHY01WYUV1YVhXanBMMG5P
      MUlyYTZmMWFOOXBXM2ovbTRwR21LU1kKLS0tIHNUK3lOWUdaZEw0RU9YTTYrSVE2
      VmRydnBaN0pHUktDS2MzNm9FeE9BODQKxs8aEUKfV5gtgh2gCVuUdB/ypLdsUZsH
      ab+zf0YKZiXCWdTvDx19G61IeVUNfORv+Olvxt39wmIa+Tsq63HzNw==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-20T01:25:43Z"
  mac: ENC[AES256_GCM,data:7aI/KeGQN9TsZBlOXYNwaDg+H+C82dbjCMwPcJSB9GO7GyfrEnowz1Bh60fyYM5OShgaq7kHx3LE4EOKBFEHPR8/IphJ8ALoOOmQgkLgp/GCeVn56QZBo+PGduR5FM5dPRM5lzom0VMlxcLLD3QcGisxE40FaTc5/skb0lhKh/E=,iv:asZeIShzpo58txcP3VTyYnqYhtlU7dYm673r8Faq3aA=,tag:hC6PIqvDWKce0cHXhXBI4w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
