# yaml-language-server: $schema=https://k8s-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: snikket-tls
spec:
  secretName: snikket-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  dnsNames:
    - "snikket.${HOME_DOMAIN}"
    - "groups.snikket.${HOME_DOMAIN}"
    - "share.snikket.${HOME_DOMAIN}"
