# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app homelab-assistant-crds
  namespace: "${KS_NAMESPACE}"
spec:
  targetNamespace: &namespace volsync-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/volsync-system/homelab-assistant/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: "${KS_GIT_REPO_NAME}"
  wait: true
  interval: "${KS_INTERVAL}"
  retryInterval: "${KS_RETRY_INTERVAL}"
  timeout: "${KS_TIMEOUT}"
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app homelab-assistant
  namespace: "${KS_NAMESPACE}"
spec:
  targetNamespace: &namespace volsync-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/volsync-system/homelab-assistant/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: "${KS_GIT_REPO_NAME}"
  dependsOn:
  - name: homelab-assistant-crds
  wait: true
  interval: "${KS_INTERVAL}"
  retryInterval: "${KS_RETRY_INTERVAL}"
  timeout: "${KS_TIMEOUT}"
  postBuild:
    substitute:
      APP: *app
      NAMESPACE: *namespace
---
# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app homelab-assistant-monitor
  namespace: "${KS_NAMESPACE}"
spec:
  targetNamespace: &namespace volsync-system
  commonMetadata:
    labels:
      app.kubernetes.io/name: *app
  path: ./kubernetes/apps/volsync-system/homelab-assistant/monitor
  prune: true
  sourceRef:
    kind: GitRepository
    name: "${KS_GIT_REPO_NAME}"
  dependsOn:
  - name: homelab-assistant
  wait: false
  interval: "${KS_INTERVAL}"
  retryInterval: "${KS_RETRY_INTERVAL}"
  timeout: "${KS_TIMEOUT}"
