# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kustomize.toolkit.fluxcd.io/kustomization_v1.json
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: startup-op-onepassword-connect
  namespace: flux-system
spec:
  path: ./kubernetes/deployments/startup/op/onepassword-connect/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: k8s-kflix
  wait: true
  interval: 30m
  retryInterval: 1m
  timeout: 5m
