# yaml-language-server: $schema=https://k8s-schemas.pages.dev/kubernetes/v1.30.1/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:Z04N8UNCOmdDXLdWhu4NG/X5WfrcgySNQOfoeFtQDRVr49gEClvUoQ==,iv:gvsO8yrcS9mZRCLHz0s6O8vrX+pknWHo/KiwiZ6fseQ=,tag:qz1t3yIpzlq2uWqRWkK9Iw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
  - recipient: age1tk7tw0625mspavxe8lvv348p58ydqw6r04sxcjq76m98nan2lsnq3dhvxd
    enc: |
      -----BEGIN AGE ENCRYPTED FILE-----
      YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvSE50NlYva2k1MTh6dlVH
      aldCaUt4cU5EMkJoNVZvbWhVaHlJa3ltRHhNCmM0bVJIMkRtNGZoa0RiS2ZzTkRI
      YmNBWCtvWklHY3NoM2VxK1lZR1RKL3MKLS0tIGRQNDRlQms5YUhQS2JaUTJ5a2xl
      Z2hjQm5PR052cFREc3Rvcm82Qk5rcVkKAFP3mEtQZ+3jfYMrgjoDrWmbKoNlewGV
      dIJMa85wEX1+bBClnizRSlOcsazy7whn+rz0Q/9pPn1BsCuSpHztAA==
      -----END AGE ENCRYPTED FILE-----
  lastmodified: "2024-05-19T23:19:18Z"
  mac: ENC[AES256_GCM,data:wK4PgXym+Rff1SwYMGEw+2x7IXF4u1PplQDel/EfOpBg9g8s3V07nbNqWrm21u27f8xkvh8yl86glO0YjcA/LXJ5wqmMV/WG9mQ+M8qwLxiQVgTq+HyR9QzW4Yllvh0MM9x91hNoJ9PObJNZY51EU9nlbYu2zUPrUPIOvng1gdM=,iv:f2p4Rc/fPzO2ytTJ1vbyKBiixPdj5S+lOXgmZb5zua0=,tag:7vb0WrTtdNQT4jkaQeAi0w==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  version: 3.8.1
